version: "1.0"
services:
  db:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  